Repository pygraphviz/pygraphviz, pull requests merged in 2024-01, with the labels that each got.

#494 Use pydata-sphinx-theme
  doc/source/_templates/dev_banner.html
  doc/source/_templates/eol_banner.html
  doc/source/_templates/layout.html
  doc/source/conf.py
  doc/source/index.rst
  requirements/doc.txt
Labels: type: Documentation

#496 Use dependabot
  .github/dependabot.yml
Labels: type: Maintenance

#495 Add version switcher
  doc/source/_static/version_switcher.json
  doc/source/conf.py
Labels: type: Documentation

#502 Update the year
  LICENSE
  README.rst
Labels: type: Maintenance

#504 Update license information
  LICENSE
  doc/source/reference/index.rst
  doc/source/reference/legal.rst
Labels: type: Maintenance

#503 Stop building pdf of the docs
  .circleci/config.yml
  .github/workflows/circleci.yml
  .github/workflows/deploy-docs.yml
  doc/Makefile
Labels: type: Maintenance

#506 Move release notes
  doc/source/contribute.rst
  doc/source/developer/contribute.rst
  doc/source/developer/index.rst
  doc/source/developer/release.rst
  doc/source/index.rst
  doc/source/reference/api_notes.rst
  doc/source/reference/index.rst
  doc/source/reference/news.rst
  doc/source/release/index.rst
  doc/source/release/old_release_log.rst
  doc/source/tutorial.rst
Labels: type: Documentation

#508 Remove outdated pystrings.swg
  pygraphviz/graphviz.i
  pygraphviz/graphviz_wrap.c
  pystrings.swg
Labels: type: Bug fix, type: Maintenance

#509 Update CI tests
  .github/workflows/test.yml
Labels: type: Maintenance

#510 Update pre-commit repos
  .pre-commit-config.yaml
  examples/plot_miles.py
  examples/plot_simple.py
  examples/plot_star.py
  examples/skip_utf8_encoding.py
  pygraphviz/agraph.py
Labels: type: Maintenance
