Repository pygraphviz/pygraphviz, pull requests merged in 2024-09, with the labels that each got.

#514 Avoid subprocess window creation with agraph.AGraph._run_prog
  pygraphviz/agraph.py
Labels: type: Enhancement

#538 Fix formatting
  pygraphviz/agraph.py
Labels: type: Maintenance

#539 Test on Python 3.13
  .github/workflows/conda-macos.yml
  .github/workflows/conda-ubuntu.yml
  .github/workflows/conda-windows.yml
  .github/workflows/test.yml
Labels: type: Maintenance

#540 Use ruff and update pre-commit config
  .github/workflows/conda-macos.yml
  .github/workflows/conda-ubuntu.yml
  .github/workflows/conda-windows.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  examples/plot_simple.py
  examples/plot_star.py
  examples/skip_django_simple.py
  pygraphviz/agraph.py
  pygraphviz/graphviz.py
  pygraphviz/tests/test_attribute_defaults.py
  pygraphviz/tests/test_close.py
  pygraphviz/tests/test_graph.py
  pygraphviz/tests/test_layout.py
  pygraphviz/tests/test_repr_mimebundle.py
  pygraphviz/tests/test_scraper.py
  pygraphviz/tests/test_unicode.py
  pyproject.toml
Labels: type: Maintenance

#542 Support Python 3.13
  pyproject.toml
Labels: type: Documentation

#543 Drop support for Python 3.10 (SPEC 0)
  .circleci/config.yml
  .github/workflows/conda-macos.yml
  .github/workflows/conda-ubuntu.yml
  .github/workflows/conda-windows.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  INSTALL.txt
  pyproject.toml
Labels: type: Maintenance
