Repository pygraphviz/pygraphviz, pull requests merged in 2025-02, with the labels that each got.

#550 Bump up CI builds, test with latest windows graphviz release
  .github/workflows/conda-macos.yml
  .github/workflows/conda-ubuntu.yml
  .github/workflows/conda-windows.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: type: Maintenance

#551 DOC: remove pip install as recommendation
  INSTALL.txt
Labels: type: Documentation

#552 DOC: update install docs with link to graphviz 12.2.1 for windows
  INSTALL.txt
Labels: type: Documentation

#554 Update fedora tests
  .github/workflows/test.yml
Labels: type: Maintenance

#557 Update pre-commit
  .pre-commit-config.yaml
  pygraphviz/__init__.py
  requirements/developer.txt
Labels: type: Maintenance

#559 More precise allocation for string copy in SWIG glue
  pygraphviz/graphviz.i
  pygraphviz/graphviz.py
  pygraphviz/graphviz_wrap.c
Labels: type: Bug fix
